export const ADD_STARSHIP = "ADD_STARSHIP"
export const REMOVE_STARSHIP = "REMOVE_STARSHIP"
export const CLEAR_STARSHIPS = "CLEAR_STARSHIPS"

export const SET_AVAILABLE_STARSHIPS = "SET_AVAILABLE_STARSHIPS"
export const CLEAR_AVAILABLE_STARSHIPS = "CLEAR_AVAILABLE_STARSHIPS"

export const SET_CONFIG = "SET_CONFIG"
export const SET_SEARCH = "SET_SEARCH"

export const SET_COMPARE_RESULTS = "SET_COMPARE_RESULTS"
export const CLEAR_COMPARE_RESULTS = "CLEAR_COMPARE_RESULTS"



